### ISSUE TITLE
Deploying via portainer, need som help with error

### ISSUE THREAD

**Issue by Japhys** [maxdotio/neural-solr#2]
I found this and am very interested to give this a spin. I tried to use a stack in portainer and had to adjust a few things to get it working, the "depends on:" section. Still I get an error. Any suggestions?

```
version: '3.8' 
services:

  mighty_1:
    build: mighty/.
    container_name: mighty_1
    environment:
      - "MIGHTY_PORT=5050"
    expose:
      - 5050
    ports:
      - 5050:5050
    networks:
      - neural_solr_net

  mighty_2:
    build: mighty/.
    container_name: mighty_2
    environment:
      - "MIGHTY_PORT=5051"
    expose:
      - 5051
    ports:
      - 5051:5051
    networks:
      - neural_solr_net

  solr:
    build:
      context: solr/.
      dockerfile: Dockerfile
    container_name: neural_solr
    ports:
      - 8983:8983 
    environment:
      - ZK_HOST=neural_zk:2181
      - SOLR_HOST=0.0.0.0
    networks:
      - neural_solr_net
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.5.5
    container_name: neural_zk
    hostname: neural_zk
    ports: 
      - 2181:2128
    networks:
      - neural_solr_net

  search_app:
    build: app/.
    container_name: search_app
    expose:
      - 8000
    ports:
      - 8999:8000
    networks:
      - neural_solr_net
    depends_on:
      - mighty_1
      - mighty_2
      - zookeeper
      - solr

networks:
  neural_solr_net:
```

error has to do with app/.`

failed to deploy a stack: zookeeper Pulling 8d691f585fa8 Pulling fs layer 3da6fe7ff2ef Pulling fs layer 02c32ad92c0d Pulling fs layer c5b17f485691 Pulling fs layer 2728b1fc0ddd Pulling fs layer cb6af38fc7a6 Pulling fs layer dcc97da0d7cf Pulling fs layer a4e51360fdda Pulling fs layer c5b17f485691 Waiting dcc97da0d7cf Waiting 2728b1fc0ddd Waiting a4e51360fdda Waiting cb6af38fc7a6 Waiting 8d691f585fa8 Downloading [> ] 278.5kB/27.11MB 02c32ad92c0d Downloading [==================================================>] 209B/209B 02c32ad92c0d Verifying Checksum 02c32ad92c0d Download complete 8d691f585fa8 Downloading [=====================> ] 11.43MB/27.11MB 3da6fe7ff2ef Downloading [> ] 33.4kB/3.249MB 8d691f585fa8 Downloading [======================================> ] 20.63MB/27.11MB 3da6fe7ff2ef Downloading [===============================================> ] 3.077MB/3.249MB 3da6fe7ff2ef Downloading [==================================================>] 3.249MB/3.249MB 3da6fe7ff2ef Download complete 8d691f585fa8 Verifying Checksum 8d691f585fa8 Download complete 8d691f585fa8 Extracting [> ] 294.9kB/27.11MB 8d691f585fa8 Extracting [==================> ] 10.03MB/27.11MB c5b17f485691 Downloading [> ] 409.6kB/40.45MB 8d691f585fa8 Extracting [=================================> ] 17.99MB/27.11MB c5b17f485691 Downloading [==============> ] 11.93MB/40.45MB 8d691f585fa8 Extracting [=============================================> ] 24.77MB/27.11MB cb6af38fc7a6 Downloading [> ] 54.67kB/5.382MB c5b17f485691 Downloading [============================> ] 23.4MB/40.45MB 8d691f585fa8 Extracting [================================================> ] 26.25MB/27.11MB 2728b1fc0ddd Downloading [=====================> ] 771B/1.804kB 2728b1fc0ddd Downloading [==================================================>] 1.804kB/1.804kB 2728b1fc0ddd Verifying Checksum 2728b1fc0ddd Download complete 8d691f585fa8 Extracting [==================================================>] 27.11MB/27.11MB cb6af38fc7a6 Downloading [===============================================> ] 5.077MB/5.382MB cb6af38fc7a6 Verifying Checksum cb6af38fc7a6 Download complete c5b17f485691 Downloading [=====================================> ] 30.38MB/40.45MB 8d691f585fa8 Pull complete 3da6fe7ff2ef Extracting [> ] 32.77kB/3.249MB c5b17f485691 Verifying Checksum c5b17f485691 Download complete 3da6fe7ff2ef Extracting [==================================================>] 3.249MB/3.249MB 3da6fe7ff2ef Pull complete 02c32ad92c0d Extracting [==================================================>] 209B/209B 02c32ad92c0d Extracting [==================================================>] 209B/209B 02c32ad92c0d Pull complete c5b17f485691 Extracting [> ] 426kB/40.45MB c5b17f485691 Extracting [===========> ] 8.946MB/40.45MB c5b17f485691 Extracting [=========================> ] 20.45MB/40.45MB a4e51360fdda Downloading [==================================================>] 749B/749B a4e51360fdda Verifying Checksum a4e51360fdda Download complete dcc97da0d7cf Downloading [> ] 107.8kB/10.6MB c5b17f485691 Extracting [===============================> ] 25.13MB/40.45MB dcc97da0d7cf Downloading [==> ] 439.2kB/10.6MB c5b17f485691 Extracting [====================================> ] 29.39MB/40.45MB dcc97da0d7cf Downloading [=====> ] 1.127MB/10.6MB c5b17f485691 Extracting [==========================================> ] 34.08MB/40.45MB dcc97da0d7cf Downloading [===========> ] 2.504MB/10.6MB c5b17f485691 Extracting [================================================> ] 39.19MB/40.45MB c5b17f485691 Extracting [==================================================>] 40.45MB/40.45MB c5b17f485691 Extracting [==================================================>] 40.45MB/40.45MB dcc97da0d7cf Downloading [=========================> ] 5.469MB/10.6MB c5b17f485691 Pull complete 2728b1fc0ddd Extracting [==================================================>] 1.804kB/1.804kB 2728b1fc0ddd Extracting [==================================================>] 1.804kB/1.804kB 2728b1fc0ddd Pull complete cb6af38fc7a6 Extracting [> ] 65.54kB/5.382MB dcc97da0d7cf Verifying Checksum dcc97da0d7cf Download complete cb6af38fc7a6 Extracting [==================================================>] 5.382MB/5.382MB cb6af38fc7a6 Pull complete dcc97da0d7cf Extracting [> ] 131.1kB/10.6MB dcc97da0d7cf Extracting [====> ] 917.5kB/10.6MB dcc97da0d7cf Extracting [==================================================>] 10.6MB/10.6MB dcc97da0d7cf Extracting [==================================================>] 10.6MB/10.6MB dcc97da0d7cf Pull complete a4e51360fdda Extracting [==================================================>] 749B/749B a4e51360fdda Extracting [==================================================>] 749B/749B a4e51360fdda Pull complete zookeeper Pulled unable to prepare context: path "app/." not found `
